name: quran
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.1.8
  carousel_slider: ^4.2.1
  dio: ^5.4.1
  path_provider: ^2.1.2
  google_fonts: ^6.2.1
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    # - assets/quran/page-images/

  fonts:
    - family: Me Quran
      fonts:
        - asset: assets/fonts/Me-Quran-Regular.ttf
    - family: Uthmanic Script
      fonts:
        - asset: assets/fonts/Uthmanic-Script-HAFS-Regular.otf
    - family: Kitab Regular
      fonts:
        - asset: assets/fonts/Kitab-Regular.ttf
