name: quran
description: "A cross platform Holy Quran App made with flutter!"
publish_to: "none"
version: 0.1.0+0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.1.8
  carousel_slider: ^4.2.1
  dio: ^5.4.1
  path_provider: ^2.1.2
  google_fonts: ^6.2.1
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  args: ^2.4.2
  flutter_launcher_icons: "^0.13.1"
  msix: ^3.16.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    # - assets/quran/page-images/

  fonts:
    - family: Me Quran
      fonts:
        - asset: assets/fonts/Me-Quran-Regular.ttf
    - family: Uthmanic Script
      fonts:
        - asset: assets/fonts/Uthmanic-Script-HAFS-Regular.otf
    - family: Kitab Regular
      fonts:
        - asset: assets/fonts/Kitab-Regular.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/quran-logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/quran-logo.png"
    background_color: "#EDD681"
    theme_color: "#151515"
  windows:
    generate: true
    image_path: "assets/images/quran-logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/quran-logo.png"

msix_config:
  display_name: Quran
  publisher_display_name: Muhammed Rahif
  identity_name: com.example.quran
  msix_version: 1.0.0.0
  logo_path: assets/images/quran-logo.png
  capabilities: internetClient #, location, microphone, webcam
  output_path: build/windows
  output_name: Quran
  install_certificate: false
