name: Gh-Pages Release
on:
  workflow_dispatch:
jobs:
  build_deploy_gh_pages:
    name: Build and Deploy to Gh-Pages
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /quran/
